# Generated by Django 3.1.7 on 2021-03-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='cat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cat'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='dog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.dog'),
        ),
    ]
