# Generated by Django 3.1.7 on 2021-03-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210310_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='dog',
        ),
        migrations.AlterField(
            model_name='feeding',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cat'),
        ),
    ]
